apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: K8S-Argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vikash-8090-Yadav/K8S-Argocd_Project
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true 
